services:
  sonarqube:
    image: sonarqube:${SONARQUBE_VERSION:-latest}
    container_name: sonarqube
    depends_on:
      - db
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=${SONARQUBE_JDBC_USERNAME:-sonar}
      - SONAR_JDBC_PASSWORD=${SONARQUBE_JDBC_PASSWORD:-sonar}
      - SONAR_WEB_JAVAOPTS=-Xmx2G -Xms1G
      - SONAR_CE_JAVAOPTS=-Xmx2G -Xms1G
      - SONAR_SEARCH_JAVAOPTS=-Xmx1G -Xms1G
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "${SONARQUBE_PORT:-9010}:9000"
    networks:
      - sonarnet
    restart: unless-stopped
    # Recommended for production environments
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-sonar}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sonar}
      - POSTGRES_DB=${POSTGRES_DB:-sonar}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarnet
    restart: unless-stopped

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data: